"""Scenario-specific employee decision semantics for FactoryBench-100.

The scenario catalog defines the Oracle operation.  This module defines the
business question behind that operation: what must be reconciled, what is
eligible, what is excluded, which independent constraint matters, and which
alternatives a real employee would compare.  Keeping all 100 entries explicit
prevents a superficially varied task set from collapsing onto one hidden
material-shortage template.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ScenarioDecisionSpec:
    mode: str
    subject: str
    scope_label: str
    eligible_label: str
    excluded_label: str
    constraint_label: str
    external_label: str
    capacity_label: str
    unit: str
    options: tuple[str, str, str]
    recommended_index: int
    source_document: str


def _s(
    mode: str,
    subject: str,
    scope_label: str,
    eligible_label: str,
    excluded_label: str,
    constraint_label: str,
    external_label: str,
    capacity_label: str,
    unit: str,
    options: tuple[str, str, str],
    recommended_index: int,
    source_document: str,
) -> ScenarioDecisionSpec:
    return ScenarioDecisionSpec(
        mode,
        subject,
        scope_label,
        eligible_label,
        excluded_label,
        constraint_label,
        external_label,
        capacity_label,
        unit,
        options,
        recommended_index,
        source_document,
    )


SCENARIO_DECISION_SPECS: dict[str, ScenarioDecisionSpec] = {
    # Customer commitment
    "Commit one pallet of Luma lamps": _s("plan", "one pallet of Luma lamps", "revision-C bulbs required for 120 four-lamp kits", "nettable LMP-BULB-12 units", "quarantined and reserved bulb units", "material readiness versus the protected assembly calendar", "Rainier's confirmed standard and expedite dates", "qualified non-displacing WC-2 slots", "EA", ("standard_plan", "expedite_bulbs", "add_weekend_shift"), 0, "lamp BOM and launch commitment"),
    "Split a defense order around an export hold": _s("quantity", "defense order SO-47002", "total ordered controller quantity", "domestic lines released by trade compliance", "export-controlled lines awaiting a license", "release only quantities whose destination and end-use are cleared", "counsel's export-license decision date", "domestic build capacity that preserves the held line", "EA", ("wait_for_full_license", "release_domestic_quantity", "cancel_restricted_line"), 1, "export classification and end-use register"),
    "Recover a customer promise after a carrier rollover": _s("schedule", "customer order SO-47003", "finished units committed to the rolled sailing", "units already packed and carrier-ready", "units missing the rolled cutoff", "new sailing cutoff plus port transit and customer dock window", "carrier's confirmed next-sailing and airfreight quotes", "packing capacity before each cutoff", "EA", ("accept_next_sailing", "split_air_and_ocean", "move_all_units_by_air"), 1, "carrier rollover and delivery calendar"),
    "Replace an obsolete configuration before fulfillment": _s("identity", "obsolete controller configuration on SO-47004", "open order lines at the obsolete revision", "lines inside the approved substitute effectivity", "completed or out-of-effectivity serials", "engineering change, customer configuration, and serial breakpoint must all match", "supplier availability for the approved substitute", "remaining configuration-validation window", "LINES", ("apply_approved_substitute", "wait_for_original_part", "request_customer_deviation"), 0, "substitution effectivity matrix"),
    "Stop supply for a duplicated customer release": _s("quantity", "duplicate EDI release on SO-47005", "purchase quantity created from the suspect release", "unconsumed quantity traceable only to the duplicate", "quantity reserved or pegged to legitimate demand", "customer PO, line, revision, quantity, and ship window must all duplicate an existing release", "supplier cancellation cutoff", "remaining valid demand coverage", "EA", ("retain_both_releases", "cancel_duplicate_supply", "freeze_all_customer_supply"), 1, "EDI duplicate-release comparison"),

    # Production control
    "Release the flight-test controller build": _s("plan", "flight-test controller work order", "released build quantity at the flight revision", "components with released certs and nettable stock", "parts on quality hold or at the wrong revision", "drawing, deviation, material, and dispatch release gates", "approved recovery supply for the last shortage", "qualified flight-test assembly window", "EA", ("release_complete_build", "release_partial_build", "keep_order_unreleased"), 0, "flight-build release checklist"),
    "Resequence burn-in ahead of final assembly": _s("schedule", "burn-in operation on WO-0007", "burn-in chamber-hours required", "open certified chamber-hours before final assembly", "protected qualification runs", "precedence, cure time, and completed quantities cannot be violated", "contract chamber availability", "finite burn-in and final-assembly windows", "HR", ("keep_current_sequence", "move_burn_in_forward", "outsource_burn_in"), 1, "dispatch and chamber-load schedule"),
    "Insert an approved rework operation": _s("identity", "failed inspection on WO-0008", "nonconforming units named by the disposition", "units inside the approved rework scope", "scrapped or already accepted units", "quality disposition and routing revision must name the same lot and operation", "rework instruction release", "qualified rework-cell window", "EA", ("scrap_affected_units", "insert_approved_rework", "use_as_is_deviation"), 1, "nonconformance disposition and rework router"),
    "Replace a constrained relay on an active order": _s("quantity", "relay material line on WO-0009", "remaining relay demand at the active revision", "approved substitute stock after conversion ratio", "original relays already issued or substitute lots outside effectivity", "substitute effectivity, conversion ratio, and available lot status", "supplier replenishment for the original relay", "remaining install-window capacity", "EA", ("wait_for_original_relay", "apply_approved_relay_substitute", "reduce_build_quantity"), 1, "relay substitute and effectivity matrix"),
    "Assign certified contract labor to wiring": _s("schedule", "wiring operation on WO-0010", "wiring labor-hours still required", "qualified contract hours inside the operation window", "hours from expired certifications or conflicting assignments", "worker certification, approved rate, and remaining assignment capacity", "agency's confirmed worker roster", "wiring bench and supervisor coverage", "HR", ("wait_for_internal_labor", "assign_certified_contractor", "authorize_overtime_crew"), 1, "skills, rate, and labor-capacity roster"),

    # Material execution
    "Issue the earliest-expiry conforming adhesive": _s("quantity", "adhesive issue to WO-0011", "adhesive quantity required by operation 10", "FEFO lot quantity with valid shelf life and certificate", "expired, reserved, or wrong-revision adhesive", "issue the earliest-expiry conforming lot without breaking its reservation", "replacement-lot arrival", "operation consumption window", "KG", ("issue_fefo_conforming_lot", "issue_later_expiry_lot", "request_shelf_life_waiver"), 0, "lot shelf-life and certificate ledger"),
    "Return unused copper from a canceled operation": _s("quantity", "unused copper on canceled operation 20", "quantity previously issued to the canceled operation", "physically counted unconsumed copper", "scrap, consumed, or unverified copper", "return cannot exceed issued less consumed and must preserve project ownership", "recount and discrepancy resolution", "stores receiving window", "KG", ("return_verified_excess", "leave_material_in_wip", "adjust_full_issued_quantity"), 0, "issue-consumption and physical-count reconciliation"),
    "Correct a wrong-lot scan before consumption": _s("identity", "wrong-lot inventory scan", "candidate scan and lot records", "scan matching item, location, timestamp, and supervisor confirmation", "similar scans from other lots or operations", "reverse the erroneous lot movement before posting the verified lot", "scanner-log retention", "transaction interface cutoff", "RECORDS", ("reverse_and_post_verified_lot", "edit_lot_master", "leave_scan_for_period_end"), 0, "scanner log and lot-correction crosswalk"),
    "Report serial-controlled panel completion": _s("quantity", "serial-controlled panel completion", "serials assigned to the final operation", "serials with every traveler signature and passed test", "missing-signature, duplicate, or failed-test serials", "completed quantity must equal the distinct eligible serial set", "missing signature resolution", "final-operation completion window", "SERIALS", ("complete_eligible_serials", "complete_header_quantity", "hold_all_serials"), 0, "electronic traveler and serial ledger"),
    "Post calibrated test-bench labor actuals": _s("quantity", "test-bench resource actual", "signed test-bench hours presented for posting", "hours inside the calibration window and correct operation", "duplicate, out-of-window, or unsigned hours", "employee, operation, rate, and calibration interval must reconcile", "corrected timecard availability", "open resource-transaction period", "HR", ("post_supported_labor", "hold_for_timecard_correction", "post_supervisor_estimate"), 0, "timecard, rate, and calibration reconciliation"),

    # Capacity recovery
    "Reroute assembly after a spindle failure": _s("schedule", "assembly operation exposed to spindle failure", "machine-hours needed to preserve the order", "qualified alternate-cell hours with tooling and operator", "down primary-cell hours and protected alternate load", "alternate must be active, qualified, and non-displacing", "repair team's spindle restoration estimate", "finite load on each qualified assembly cell", "HR", ("wait_for_primary_cell", "reroute_to_qualified_cell", "add_unapproved_night_shift"), 1, "downtime diagnosis and alternate-cell load"),
    "Recover output after a certified welder absence": _s("schedule", "welding backlog after absence", "certified welding hours required", "available qualified replacement hours", "uncertified or already assigned labor-hours", "process certification and shift availability must overlap", "agency replacement arrival", "weld-booth and inspector capacity", "HR", ("accept_delayed_output", "assign_qualified_alternate_welder", "use_uncertified_labor"), 1, "skills matrix and shift roster"),
    "Move outsourced coating around a supplier outage": _s("schedule", "outside-coating operation", "coating quantity due before assembly", "quantity the approved alternate can accept", "WIP already at the closed supplier or outside alternate capacity", "alternate source, PO line, process spec, and ship window must match", "alternate coater's confirmed turnaround", "downstream cure and assembly slots", "EA", ("wait_for_incumbent_recovery", "reroute_to_approved_coater", "skip_coating_operation"), 1, "supplier outage and alternate-source capacity"),
    "Apply approved weekend overtime to backlog": _s("schedule", "weekend backlog recovery", "operation-hours in the approved backlog scope", "authorized weekend hours with qualified crew", "hours outside the named orders or approval cap", "only listed orders and cost center may use the overtime window", "temporary labor availability", "weekend workcenter and inspection coverage", "HR", ("keep_weekday_sequence", "apply_approved_weekend_overtime", "add_second_unapproved_shift"), 1, "overtime authorization and finite schedule"),
    "Hold production for an expired torque-tool calibration": _s("identity", "torque operation using an expired tool", "open serials exposed after calibration expiry", "serials completed before expiry with valid trace", "post-expiry serials and unverified torque records", "production stays held until a calibrated tool and corrective work exist", "calibration provider's earliest service date", "qualified replacement-tool availability", "SERIALS", ("hold_exposed_serials_and_open_maintenance", "continue_with_expired_tool", "release_all_completed_serials"), 0, "calibration certificate and serial exposure report"),

    # Corrective maintenance
    "Open repair for a failed servo drive": _s("schedule", "failed servo drive ASSET-021", "repair-hours in the diagnosed failure scope", "qualified electrical labor and stocked parts", "unavailable parts and conflicting shop load", "alarm history, diagnostic code, and service-manual procedure must agree", "OEM drive-module arrival", "qualified electrical-shop window", "HR", ("open_internal_corrective_repair", "exchange_with_oem", "operate_until_next_shutdown"), 0, "fault history and servo service procedure"),
    "Extend a pump repair after teardown findings": _s("plan", "pump repair MWO-0022", "seal housings required by the approved teardown scope", "seal housings in stock and eligible for this repair", "seal housings quarantined or reserved, plus damage outside the approved scope", "approved scope change, part readiness, and qualified repair window", "seal-housing standard and expedite dates", "electrical-shop base and recovery slots", "EA", ("standard_repair_plan", "expedite_seal_housing", "move_to_overtime_repair"), 1, "teardown scope, parts, and shop calendar"),
    "Move a repair to the qualified electrical shop": _s("schedule", "maintenance operation requiring electrical qualification", "repair-hours remaining", "open hours in qualified electrical shops", "mechanical-only shops and protected electrical work", "shop qualification, active status, tooling, and capacity must all pass", "contract electrical-shop availability", "internal electrical-shop load", "HR", ("wait_in_current_shop", "move_to_qualified_electrical_shop", "send_to_unqualified_fast_shop"), 1, "shop qualification and maintenance load"),
    "Attach the vendor diagnostic report to maintenance": _s("identity", "vendor diagnostic report for ASSET-024", "candidate diagnostic documents", "document matching asset serial, failure date, and checksum", "reports for similar assets or superseded revisions", "only the immutable matching report may be linked to the open order", "vendor's signed report revision", "maintenance document-review window", "FILES", ("attach_matching_report", "attach_latest_named_report", "request_new_diagnostic"), 0, "diagnostic report identity and checksum register"),
    "Convert a repeated bearing alarm into planned work": _s("forecast", "repeated bearing alarm on ASSET-025", "qualifying alarms inside the reliability window", "distinct alarms meeting duration and severity thresholds", "duplicate telemetry and acknowledged nuisance events", "the third qualifying alarm plus reliability approval triggers planned work", "bearing-kit readiness", "next production-safe maintenance window", "ALARMS", ("create_recurring_program", "open_one_time_repair", "continue_monitoring"), 0, "alarm history and reliability trigger matrix"),

    # Preventive maintenance
    "Advance lubrication after a meter spike": _s("forecast", "meter-based lubrication program", "meter usage since last lubrication", "usage accepted after removing reset and duplicate readings", "invalid spikes and readings before the last service", "effective meter threshold and blackout calendar determine the due date", "lubricant-kit readiness", "production-safe lubrication window", "HOURS", ("advance_program_forecast", "keep_calendar_due_date", "generate_emergency_work"), 0, "meter history and lubrication threshold"),
    "Generate the quarterly compressor forecast": _s("forecast", "quarterly compressor program", "eligible active compressors in the forecast horizon", "assets with approved quarterly pattern and no existing forecast", "inactive assets, blackout dates, and duplicate forecasts", "generate only due rows inside the bounded horizon", "contractor coverage by month", "shutdown calendar availability", "ASSETS", ("generate_bounded_forecast", "forecast_all_asset_rows", "defer_entire_quarter"), 0, "compressor roster and maintenance calendar"),
    "Create due work for guarded saw inspections": _s("forecast", "guarded-saw inspection forecast", "forecast rows due before the next shutdown", "due rows with active assets and safe shutdown windows", "already generated, inactive, or blackout-window rows", "one work order per eligible forecast row without duplication", "guard-inspection kit readiness", "approved shutdown windows", "WORK_ORDERS", ("generate_due_work_only", "generate_full_year_work", "defer_to_next_shutdown"), 0, "inspection forecast and shutdown reconciliation"),
    "Create a contamination-control program": _s("forecast", "contamination-control maintenance program", "assets named by the sanitation standard", "active food-contact assets with approved frequencies", "inactive, non-contact, or already covered assets", "signed standard, asset criticality, and quality approval define the program", "sanitation contractor capacity", "approved cleaning blackout windows", "ASSETS", ("create_scoped_program", "copy_existing_generic_program", "include_all_plant_assets"), 0, "sanitation standard and asset criticality roster"),
    "Link the revised lockout procedure to PM work": _s("identity", "revised lockout procedure", "candidate procedure revisions", "released revision effective for the asset and work date", "draft, superseded, or wrong-asset procedures", "document number, revision, approval, and asset applicability must match", "safety office release confirmation", "PM work-order start window", "FILES", ("link_released_procedure", "link_latest_filename", "delay_work_for_new_revision"), 0, "lockout revision and applicability matrix"),

    # Strategic procurement
    "Award the enclosure tooling package": _s("financial", "enclosure tooling sourcing event", "best-value bid quoted total before commercial exclusions", "supported landed cost of the technically acceptable best-value bid", "unapproved options and unsupported fees on the selected bid", "technical score, landed cost, supplier status, launch capacity, and sourcing authority", "bid validity and tooling lead time", "milestone capacity against launch need", "USD", ("award_best_value_bid", "award_lowest_sticker_price", "split_unapproved_award"), 0, "technical bid and commercial evaluation"),
    "Record the supplier's expedited promise": _s("schedule", "open purchase order PO-0032", "open quantity covered by the acknowledgment", "quantity and date explicitly confirmed by the supplier", "closed lines and quantities omitted from the acknowledgment", "supplier reference, PO line, quantity, and promised date must correlate", "signed supplier acknowledgment", "downstream production need date", "EA", ("keep_existing_promise", "record_confirmed_expedited_promise", "infer_earlier_promise"), 1, "supplier acknowledgment and PO schedule"),
    "Cancel a resin order after a safety bulletin": _s("quantity", "resin PO affected by safety bulletin", "open resin quantity on named lots", "unreceived and unconsumed quantity safe to cancel", "received, consumed, or unaffected resin", "bulletin material code, lot scope, and cancellation authority", "supplier cancellation deadline", "replacement-resin coverage", "KG", ("cancel_affected_open_quantity", "cancel_entire_supplier_account", "continue_receiving_resin"), 0, "safety bulletin and open-quantity ledger"),
    "Close a fully received calibration-services PO": _s("financial", "calibration-services PO", "ordered service value", "accepted service-entry and matched invoice value", "unaccepted or unmatched value", "receipt, acceptance, invoice, and buyer approval must all be complete", "supplier's final invoice status", "current close-processing window", "USD", ("finally_close_fully_settled_po", "leave_po_open", "close_with_unmatched_balance"), 0, "service acceptance and three-way reconciliation"),
    "Create emergency supply for a line-down shortage": _s("plan", "line-down component demand", "immediate uncovered component requirement", "usable stock and firm inbound supply before need", "reserved stock and supply arriving after the line-down point", "sole-source exception, exact shortage, and emergency freight authority", "approved supplier's emergency ready date", "line recovery and receiving window", "EA", ("create_bounded_emergency_supply", "order_full_gross_demand", "wait_for_standard_replenishment"), 0, "line-down shortage and sole-source exception"),

    # Receiving control
    "Receive a lot-controlled relay shipment": _s("quantity", "relay shipment against PO-0036", "packing-slip and PO quantity", "physically counted relays with matching supplier lot and certificate", "overage, wrong lot, or uncertified units", "PO line, receipt organization, lot, certificate, and dock count must reconcile", "supplier certificate and packing slip", "inspection capacity before put-away", "EA", ("receive_supported_lot_quantity", "receive_packing_slip_total", "reject_entire_shipment"), 0, "packing slip, PO, lot, and certificate"),
    "Reject water-damaged enclosures at inspection": _s("quantity", "water-damaged enclosure receipt", "units presented for inspection", "dry units passing the inspection plan", "water-damaged units documented by dock photos", "accepted plus rejected must equal inspected and preserve carrier evidence", "supplier replacement promise", "quarantine-space capacity", "EA", ("accept_all_units", "reject_documented_damage_only", "return_entire_shipment"), 1, "dock photos and receiving inspection plan"),
    "Correct a transposed receiving quantity": _s("quantity", "receipt interface quantity error", "packing-slip quantity", "scale-ticket and physical-count quantity", "transposition overstatement", "correct only the erroneous interface transaction before delivery", "supplier-confirmed shipped quantity", "project-stores downstream requirement", "EA", ("leave_interface_quantity", "correct_to_verified_quantity", "reverse_entire_receipt"), 1, "packing slip, scale ticket, and interface row"),
    "Deliver inspected copper to project stores": _s("quantity", "accepted project copper receipt", "quantity received for the project PO", "inspection-accepted quantity with matching project and task", "rejected or common-owned quantity", "delivery must preserve project, task, lot, and accepted status", "supplier replacement for rejected copper", "project-stores handling window", "KG", ("deliver_project_accepted_quantity", "deliver_full_receipt", "move_to_common_stores"), 0, "inspection acceptance and project ownership"),
    "Return mislabeled relays to the supplier": _s("quantity", "mislabeled relay receipt", "received quantity under the affected label", "units covered by the supplier return authorization", "correctly labeled or already consumed units", "label nonconformance, lot, PO line, and RMA quantity must match", "supplier RMA and replacement date", "return-dock pickup window", "EA", ("return_authorized_quantity", "return_all_supplier_stock", "relabel_internally_without_approval"), 0, "label nonconformance and supplier RMA"),

    # Payables control
    "Validate a clean three-way-matched invoice": _s("financial", "supplier invoice INV-0041", "invoice gross amount", "PO-backed accepted-receipt amount within tolerance", "unmatched tax, freight, or quantity variance", "supplier, PO line, receipt, currency, tax, and tolerance must reconcile", "supplier PDF invoice", "open accounting and payment cycle", "USD", ("validate_matched_invoice", "place_manual_hold", "change_invoice_amount"), 0, "invoice, PO, receipt, and tolerance reconciliation"),
    "Place a freight-variance hold": _s("financial", "freight variance on INV-0042", "invoice amount including freight", "PO-supported goods and allowed charges", "freight excluded from the contract above tolerance", "hold only the documented exception with the approved reason", "supplier freight explanation", "payment-run cutoff", "USD", ("pay_invoice_as_submitted", "place_freight_variance_hold", "short_pay_without_hold"), 1, "invoice freight and PO charge policy"),
    "Release a hold after the supplier credit arrives": _s("financial", "existing invoice hold on INV-0043", "held variance amount", "credit memo applied to the same invoice and reason", "unapplied or unrelated credit value", "credit, invoice, hold, and manager release approval must match", "supplier credit memo", "next payment-run cutoff", "USD", ("keep_hold_open", "release_matched_hold", "release_all_supplier_holds"), 1, "credit memo and hold-release reconciliation"),
    "Correct payment terms from the signed contract": _s("financial", "payment terms on INV-0044", "invoice amount governed by the contract", "amount at the signed supplier-site terms", "value under an obsolete master term", "executed agreement, effective date, supplier site, and invoice must match", "signed contract terms", "discount and payment calendar", "USD", ("keep_invoice_terms", "apply_signed_contract_terms", "edit_supplier_master_globally"), 1, "executed contract and supplier-site terms"),
    "Enter a non-PO metrology invoice": _s("financial", "non-PO metrology invoice", "invoice gross amount", "approved service value with valid BU and account coding", "tax, duplicate, or unapproved service value", "supplier site, service acceptance, coding, and approval authority", "supplier invoice PDF", "current accounting-period cutoff", "USD", ("enter_approved_non_po_invoice", "invent_purchase_order_reference", "defer_to_next_period"), 0, "metrology invoice and approval coding"),

    # Supplier governance
    "Approve a conditional alternate for molded parts": _s("identity", "conditional molded-parts source", "candidate supplier sites", "site passing audit, insurance, and trial-lot quality", "expired, failed, or unapproved sites", "conditional use is limited by item, quantity, duration, and approval", "trial-lot and insurance validity", "continuity demand before incumbent recovery", "SITES", ("enable_conditional_source", "approve_supplier_globally", "stay_sole_source"), 0, "supplier audit and conditional-use scope"),
    "Escalate sole-source spend concentration": _s("financial", "sole-source spend exposure", "open and forecast spend with the supplier", "spend covered by approved mitigation actions", "unmitigated concentration above policy threshold", "exposure must combine open POs, forecast, currency, and supplier parent", "alternate-source qualification timing", "time before production exposure", "USD", ("record_bounded_mitigation", "ignore_concentration", "cancel_all_open_pos"), 0, "supplier-parent spend and mitigation workbook"),
    "Suspend orders after a sanctions-screening hit": _s("identity", "sanctions-screening match", "open supplier commitments screened", "orders tied to the confirmed legal-entity match", "false positives and unrelated affiliates", "legal entity, address, ownership, screening list, and legal direction must correlate", "legal screening disposition", "replacement-source readiness", "ORDERS", ("suspend_matched_orders", "suspend_all_similar_names", "continue_pending_review"), 0, "sanctions match and legal-entity evidence"),
    "Close a supplier remediation purchase order": _s("financial", "supplier remediation PO", "remediation milestone value", "accepted milestones with approved evidence and matched invoice", "open corrective actions or unaccepted milestones", "all CAPA deliverables and financial documents must be complete", "supplier closure evidence", "governance review window", "USD", ("close_completed_remediation_po", "close_with_open_actions", "leave_settled_po_open"), 0, "CAPA milestones and commercial closure"),
    "Open maintenance after vendor-caused equipment damage": _s("schedule", "vendor-caused equipment damage", "repair-hours and parts in the incident estimate", "work covered by vendor responsibility and available resources", "unapproved betterment or unrelated damage", "incident evidence, asset, vendor responsibility, and repair scope", "vendor recovery commitment", "production-safe repair window", "HR", ("open_vendor_incident_repair", "charge_unrelated_upgrade", "continue_running_damaged_asset"), 0, "vendor incident and repair responsibility"),

    # Quality execution
    "Create incoming inspection for plated busbars": _s("quantity", "plated busbar receipt", "received busbars under the inspection plan", "sample quantity required by lot size and severity", "units outside the lot or already inspected", "effective plan, lot, supplier, characteristic, and sample-size table", "certificate and plating-bath report", "lab inspection capacity", "EA", ("create_required_incoming_inspection", "skip_inspection_on_certificate", "inspect_entire_unrelated_receipt"), 0, "inspection-plan sampling table and receipt lot"),
    "Record failed dielectric-test samples": _s("quantity", "dielectric-test inspection", "samples tested under the plan", "samples meeting voltage and leakage limits", "failed samples outside either limit", "sample results must drive lot disposition under the effective plan", "supplier containment response", "retest and MRB window", "SAMPLES", ("record_failed_samples", "average_results_to_pass", "discard_failed_measurements"), 0, "dielectric measurements and acceptance limits"),
    "Correct a mistyped dimensional result": _s("identity", "mistyped dimensional result", "candidate measurement and source rows", "row matching sample, characteristic, instrument, and timestamp", "other samples and derived summary cells", "signed raw reading and correction approval control the exact field change", "metrology source record", "inspection-close window", "RECORDS", ("correct_exact_measurement", "overwrite_inspection_summary", "leave_typo_and_add_note"), 0, "raw measurement and correction audit trail"),
    "Quarantine an expired chemical lot": _s("quantity", "expired chemical lot", "on-hand quantity in the named lot", "quantity physically present and traceable to the expired lot", "other lots and quantity already consumed", "expiry, lot, location, and open reservations define containment scope", "replacement-lot readiness", "quarantine-location capacity", "KG", ("quarantine_expired_lot", "quarantine_all_chemical_stock", "extend_expiry_without_waiver"), 0, "lot expiry and reservation ledger"),
    "Create rework supply from a failed final inspection": _s("quantity", "failed final-inspection quantity", "units rejected by final inspection", "units with approved rework disposition and recoverable BOM", "scrap and accepted units", "supply covers only approved rework yield and component demand", "replacement-component readiness", "rework-cell capacity", "EA", ("create_scoped_rework_supply", "create_supply_for_full_order", "scrap_all_failed_units"), 0, "final inspection and rework-material calculation"),

    # Inventory control
    "Transfer a constrained relay lot between plants": _s("quantity", "relay lot transfer", "destination shortage", "source-plant available quantity after reservations", "quarantined, project-owned, or safety-stock quantity", "lot, ownership, transit, and destination reservation must remain valid", "external replenishment date", "interplant handling and transit window", "EA", ("transfer_supported_quantity", "drain_source_safety_stock", "buy_new_supply"), 0, "interplant availability and reservation ledger"),
    "Post a blind cycle-count adjustment": _s("quantity", "blind cycle count", "book quantity before count", "independently counted physical quantity", "counted units with the wrong lot or unverified ownership", "the book-to-count variance must pass the recount threshold, lot, reason-code, and supervisor controls", "recount completion", "inventory accounting cutoff", "EA", ("post_verified_count_adjustment", "force_book_quantity", "adjust_without_recount"), 0, "blind count and variance approval"),
    "Move suspect housings into quarantine": _s("quantity", "suspect housing lot", "on-hand housings in the implicated lots", "quantity inside the nonconformance serial or lot scope", "unaffected lots and already issued material", "quality scope, location, reservations, and physical quantity must correlate", "investigation completion date", "quarantine-space availability", "EA", ("move_affected_stock_to_quarantine", "quarantine_all_housings", "leave_reserved_stock_available"), 0, "nonconformance scope and lot-location ledger"),
    "Return excess project copper to common stock": _s("quantity", "excess project copper", "project copper issued or reserved", "unused quantity released by the project manager", "consumed, committed, or still-required quantity", "ownership transfer requires project/task release and physical count", "future project demand", "common-stores receiving window", "KG", ("return_released_excess", "return_all_project_stock", "retain_excess_on_project"), 0, "project ownership and excess-release record"),
    "Create supply for an approved kanban breach": _s("plan", "kanban breach", "replenishment needed to restore the approved card level", "usable stock and firm inbound within replenishment time", "reserved stock and duplicate open supply", "breach approval, card size, minimum, maximum, and open supply", "supplier or source-org replenishment", "line-side consumption window", "EA", ("create_net_kanban_supply", "order_full_maximum", "ignore_approved_breach"), 0, "kanban card, consumption, and open-supply ledger"),

    # Supply planning
    "Cover an unplanned copper demand spike": _s("plan", "copper demand spike", "revised demand inside the planning horizon", "usable on-hand and firm supply before need", "reserved, late, or unfirm coverage", "net only the incremental demand and avoid double coverage", "supplier copper lead time", "qualified production need date", "KG", ("create_net_shortage_supply", "buy_gross_revised_demand", "defer_unplanned_demand"), 0, "revised demand and supply-pegging workbook"),
    "Pull in supply after a forecast-consumption jump": _s("schedule", "forecast-consumption jump", "firm supply quantity pegged to consumed forecast", "quantity supplier confirmed for an earlier date", "unconfirmed or unrelated supply", "sales-order consumption, pegging, supplier promise, and finite dates", "supplier pull-in acknowledgment", "receiving and production window", "EA", ("keep_current_supply_date", "pull_in_confirmed_supply", "expedite_unconfirmed_quantity"), 1, "forecast consumption and supplier promise"),
    "Cancel redundant purchase supply after demand deletion": _s("quantity", "purchase supply after demand deletion", "open purchase quantity pegged to deleted demand", "unreserved, unreceived quantity with no remaining peg", "quantity reserved, received, or re-pegged", "demand deletion, pegging, downstream reservations, and cancellation cutoff", "supplier cancellation terms", "remaining demand coverage", "EA", ("cancel_redundant_open_supply", "cancel_entire_purchase_order", "retain_unneeded_supply"), 0, "demand deletion and supply-pegging audit"),
    "Replace a constrained component in planned work": _s("quantity", "planned component substitution", "planned original-component demand", "approved substitute availability after conversion ratio", "stock outside effectivity or committed elsewhere", "substitution approval, effectivity, ratio, and planned-order scope", "original and substitute lead times", "planned operation start", "EA", ("apply_planning_substitute", "wait_for_original_component", "substitute_all_open_orders"), 0, "planning substitute and availability matrix"),
    "Create constrained supply for a service allocation": _s("plan", "priority service allocation", "service demand authorized by allocation policy", "stock already reserved to that service request", "stock protected for higher priority or wrong destination", "priority, entitlement, destination, quantity, and need-by must match", "replenishment to the field destination", "service dispatch window", "EA", ("create_priority_service_supply", "take_higher_priority_stock", "create_unallocated_supply"), 0, "service allocation and entitlement register"),

    # Engineering change
    "Implement a released relay substitution": _s("identity", "released relay ECO", "open material lines evaluated for effectivity", "lines inside ECO date, revision, and serial breakpoint", "completed or out-of-effectivity lines", "ECO status, item relationship, conversion, serial break, and order state", "new relay readiness", "remaining installation window", "LINES", ("implement_effective_substitution", "change_all_historical_orders", "wait_for_old_relay"), 0, "ECO effectivity and material-line crosswalk"),
    "Move inspection to the revised routing step": _s("schedule", "routing inspection step", "open operations affected by the routing revision", "operation inside effectivity and not yet started", "completed or out-of-effectivity operations", "routing sequence, predecessor, workcenter qualification, and open state", "inspection fixture readiness", "revised routing window", "OPERATIONS", ("move_effective_inspection_step", "change_completed_operations", "keep_superseded_routing"), 0, "routing redline and operation state"),
    "Add new test-fixture capacity to an active order": _s("schedule", "test-fixture resource requirement", "fixture-hours required by the ECO", "qualified fixture-hours before test start", "uncalibrated or conflicting fixture-hours", "fixture qualification, calibration, rate, and ECO approval", "backup fixture availability", "test-operation capacity", "HR", ("add_qualified_fixture_resource", "use_uncalibrated_fixture", "defer_test_operation"), 0, "fixture qualification and resource load"),
    "Attach the released service bulletin to repair work": _s("identity", "released service bulletin", "candidate bulletin revisions", "released revision applicable to asset model and serial", "draft, superseded, or wrong-model bulletins", "bulletin number, revision, release, model, serial, and work order must match", "engineering release record", "repair-work start date", "FILES", ("attach_applicable_bulletin", "attach_latest_filename", "delay_for_future_revision"), 0, "service-bulletin effectivity register"),
    "Create a pilot work order for the revised design": _s("plan", "revised-design pilot build", "approved prototype quantity", "material and fixture coverage at the released pilot revision", "production stock protected for customer orders", "ECO release, prototype scope, lot separation, and start approval", "prototype component readiness", "isolated pilot-cell window", "EA", ("create_scoped_pilot_order", "use_customer_production_order", "build_unapproved_full_quantity"), 0, "pilot release and isolated-capacity plan"),

    # Cost accounting
    "Post missing setup labor from signed timecards": _s("financial", "missing setup labor", "signed setup hours at the approved resource rate", "hours not already posted to the correct operation", "duplicate, unsigned, or wrong-period hours", "employee, timecard, operation, rate, and period must reconcile", "timecard approval status", "open cost-posting period", "USD", ("post_supported_missing_labor", "post_estimated_hours", "defer_valid_current_period_cost"), 0, "timecard-to-resource-cost reconciliation"),
    "Reverse a duplicated copper issue": _s("financial", "duplicated copper material issue", "cost and quantity posted by the suspect scan", "one legitimate issue supported by consumption", "duplicate issue quantity and cost", "scanner identity, timestamp, lot, operation, and physical stock prove duplication", "cycle-count confirmation", "open material-cost period", "USD", ("reverse_duplicate_issue", "reverse_both_issues", "leave_duplicate_cost"), 0, "material scan and WIP-cost reconciliation"),
    "Record scrap discovered during final count": _s("quantity", "final-count scrap", "production quantity reported before final count", "good completed units physically verified", "scrap units signed by the supervisor", "good plus scrap plus prior reject must reconcile to operation input", "disposition approval", "operation close window", "EA", ("post_verified_scrap", "complete_original_quantity", "scrap_entire_batch"), 0, "final count and production-quantity bridge"),
    "Validate an outside-processing invoice": _s("financial", "outside-processing invoice", "invoice amount and billed operation quantity", "accepted supplier-operation quantity at the PO rate", "rejected, unreceived, duplicate, or rate-variance value", "PO line, receipt, inspection, invoice, currency, and tolerance", "supplier invoice and operation report", "payment and production-close cutoff", "USD", ("validate_supported_outside_invoice", "pay_billed_quantity", "hold_entire_supplier_account"), 0, "outside-processing three-way match"),
    "Reschedule incomplete WIP out of the close window": _s("schedule", "incomplete WIP at period close", "remaining operation-hours and quantity", "work demonstrably incomplete at cutoff", "completed quantity and costs belonging in the current period", "physical status, operation transactions, cutoff, and customer commitment", "missing-material recovery", "first next-period qualified slot", "HR", ("move_incomplete_wip_beyond_cutoff", "mark_order_complete", "leave_dates_inside_closed_period"), 0, "WIP physical status and close calendar"),

    # Project manufacturing
    "Move project-owned relays to the build subinventory": _s("quantity", "project-owned relay transfer", "project demand at the destination", "same-project, same-task available lot quantity", "common, other-project, quarantined, or reserved quantity", "project, task, lot, source, destination, and approval must persist", "project replenishment timing", "material-handling window", "EA", ("transfer_project_owned_quantity", "use_common_stock", "move_other_project_stock"), 0, "project ownership and lot availability"),
    "Create project supply for a customer milestone": _s("plan", "project milestone supply", "milestone demand at the authorized project task", "same-project on-hand and firm supply", "common or other-project coverage and late receipts", "milestone approval, project, task, quantity, destination, and need-by", "project-specific supplier readiness", "prototype production slot", "EA", ("create_net_project_supply", "use_other_project_inventory", "order_gross_milestone_quantity"), 0, "milestone approval and project supply netting"),
    "Align an order to the corrected project task": _s("identity", "work-order project attribution", "candidate project/task corrections", "finance-approved task matching contract and milestone", "similar project names and closed tasks", "project ID, task ID, contract line, open work order, and effective date", "finance correction record", "remaining order window", "RECORDS", ("apply_approved_project_task", "change_project_header_only", "choose_similar_task_name"), 0, "finance attribution correction and task master"),
    "Return unused project material from WIP": _s("quantity", "unused project material in WIP", "project material issued to the canceled operation", "physically counted unconsumed same-project lot", "consumed, scrapped, or other-project quantity", "operation cancellation, project ownership, lot, and count must reconcile", "future project demand", "project-stores return window", "EA", ("return_verified_project_material", "return_full_issue_quantity", "move_to_common_stock"), 0, "project issue, consumption, and count bridge"),
    "Create a project-specific prototype order": _s("plan", "project prototype order", "prototype quantity in the signed statement of work", "released-design material and project funding coverage", "customer-production stock and out-of-scope quantity", "SOW, project/task, ECO revision, quantity, and isolated start window", "prototype material readiness", "project-qualified pilot capacity", "EA", ("create_project_prototype_order", "use_standard_customer_order", "build_beyond_sow_quantity"), 0, "statement of work and prototype release"),

    # Field service supply
    "Replenish a technician's critical relay stock": _s("plan", "technician critical-relay stock", "entitled min-max replenishment quantity", "usable van and regional stock already allocated", "reserved, quarantined, or wrong-owner relays", "technician, territory, entitlement, min-max, and destination", "regional replenishment arrival", "dispatch route and depot cutoff", "EA", ("create_net_technician_replenishment", "ship_full_depot_stock", "wait_for_next_cycle"), 0, "technician entitlement and field-stock ledger"),
    "Quarantine a returned field controller": _s("quantity", "returned field controller", "serialized units received from the service event", "serials matching the RMA and customer asset", "different serials, accessories, and advance replacement", "RMA, serial, ownership, failure code, and quarantine location", "depot diagnostic timing", "secure quarantine capacity", "SERIALS", ("quarantine_matching_return", "return_to_available_stock", "quarantine_all_customer_returns"), 0, "RMA, serial, and ownership reconciliation"),
    "Open depot repair for a customer asset": _s("schedule", "customer asset depot repair", "repair-hours and parts under entitlement", "qualified depot labor and covered parts", "cosmetic work and non-entitled damage", "asset serial, entitlement, diagnosis, scope, and customer authorization", "repair-part readiness", "depot bench and technician window", "HR", ("open_entitled_depot_repair", "bill_unapproved_scope", "send_replacement_without_diagnosis"), 0, "asset entitlement and depot diagnosis"),
    "Issue a reserved spare to an emergency repair": _s("quantity", "reserved emergency spare", "spare quantity required by the repair operation", "reservation tied to the same service request and asset", "stock reserved for higher-priority events or wrong ownership", "reservation, service priority, item, lot, and repair operation", "regional replacement-stock arrival", "emergency technician window", "EA", ("issue_matching_reserved_spare", "take_other_customer_reservation", "wait_for_standard_supply"), 0, "service reservation and spare-issue ledger"),
    "Receive an advance-replacement return": _s("quantity", "advance-replacement return", "serials expected under the return obligation", "serial received with matching RMA and ownership", "replacement serial, accessory, or unrelated return", "sales order, RMA, original serial, replacement serial, and receipt organization", "customer return confirmation", "depot receiving window", "SERIALS", ("receive_matching_original_asset", "receive_replacement_serial", "close_without_return"), 0, "advance-replacement serial crosswalk"),

    # Compliance traceability
    "Contain relays named in a supplier recall": _s("quantity", "supplier recall scope", "on-hand and WIP relays from recalled supplier lots", "traceable quantity inside named lot and date ranges", "other suppliers, lots, and consumed-outside-scope units", "supplier, item, lot, receipt, genealogy, and recall effectivity", "replacement compliant supply", "quarantine and production impact window", "EA", ("contain_recalled_scope", "quarantine_all_relays", "continue_using_reserved_recall_stock"), 0, "supplier recall and lot genealogy"),
    "Attach a certificate of conformance to repair work": _s("identity", "certificate of conformance", "candidate certificates", "certificate matching supplier, lot, item, asset repair, revision, and signature", "expired, unsigned, wrong-lot, or similar-item certificates", "immutable certificate identity and applicability to the repair material", "supplier certificate confirmation", "repair release window", "FILES", ("attach_matching_certificate", "attach_latest_certificate_name", "release_without_certificate"), 0, "certificate identity and repair-material trace"),
    "Hold payment for a missing conflict-minerals report": _s("financial", "invoice missing conflict-minerals evidence", "invoice value for covered materials", "value supported by current smelter and country-of-origin evidence", "covered value lacking the required report", "policy scope, supplier, item, reporting period, and invoice lines", "supplier report delivery date", "payment-run and compliance-review cutoff", "USD", ("place_compliance_hold", "pay_without_report", "hold_unrelated_supplier_invoices"), 0, "conflict-minerals report and invoice scope"),
    "Create inspection for restricted-substance screening": _s("identity", "restricted-substance screening", "receipt lots requiring screening", "lots inside regulation and plan effectivity", "previously screened or out-of-scope lots", "item substance class, supplier, country, lot, and plan revision", "laboratory screening turnaround", "quality-lab capacity before consumption", "LOTS", ("create_scoped_compliance_inspection", "inspect_all_receipts", "release_on_supplier_statement_only"), 0, "substance classification and inspection-plan scope"),
    "Open corrective maintenance after a safety interlock bypass": _s("schedule", "safety interlock bypass", "assets and operation-hours exposed by the bypass", "confirmed affected asset with approved corrective scope", "similar alarms and unrelated assets", "safety event, asset, control circuit, isolation, and approval", "OEM interlock part arrival", "qualified controls-technician window", "HR", ("open_safety_corrective_work", "reset_alarm_without_work", "continue_under_verbal_waiver"), 0, "safety event and interlock diagnosis"),

    # Period close
    "Close a fully settled tooling PO before cutoff": _s("financial", "tooling PO close exception", "PO committed value", "accepted milestones, receipts, invoices, and payments", "open retainage or unmatched value", "all source activity must be complete before the close cutoff", "supplier final-settlement evidence", "remaining close-calendar window", "USD", ("close_fully_settled_po", "close_with_open_balance", "defer_complete_po"), 0, "tooling settlement and close checklist"),
    "Validate the final matched invoice batch item": _s("financial", "final invoice batch item", "invoice gross amount", "PO and receipt matched amount inside tolerance", "duplicate, unmatched, or post-cutoff value", "batch item, supplier, match, approval, and accounting date", "supplier invoice source", "final validation and posting cutoff", "USD", ("validate_final_matched_item", "hold_entire_batch", "post_after_cutoff"), 0, "invoice batch and close-calendar match"),
    "Hold a duplicate invoice found in reconciliation": _s("financial", "suspected duplicate invoice", "second invoice amount presented for close", "payable value unique to the second invoice after duplicate testing", "amount already represented by the original invoice", "supplier, number normalization, date, amount, PO, and attachment hash must match after legitimate tax and credit differences are removed", "supplier duplicate confirmation", "payment-run cutoff", "USD", ("hold_confirmed_duplicate", "hold_both_invoices", "pay_second_invoice"), 0, "duplicate-invoice fingerprint reconciliation"),
    "Move unfinished production beyond period end": _s("schedule", "unfinished production at cutoff", "remaining operation-hours and quantity", "work physically incomplete and unreported", "completed quantity and current-period actuals", "physical status, operation transactions, period cutoff, and revised dates", "missing input readiness", "first next-period qualified slot", "HR", ("defer_unfinished_work", "complete_order_for_close", "leave_schedule_inside_closed_period"), 0, "production status and period cutoff"),
    "Post an omitted maintenance labor charge": _s("financial", "omitted maintenance labor", "signed labor value for the maintenance order", "hours inside asset work and open period not already posted", "duplicate, unrelated, or post-cutoff hours", "technician, asset, maintenance order, rate, timecard, and period", "supervisor timecard approval", "final cost-posting window", "USD", ("post_supported_maintenance_labor", "estimate_missing_hours", "defer_current_period_charge"), 0, "maintenance timecard and cost reconciliation"),

    # Supplier operations
    "Acknowledge the anodizer's revised promise": _s("schedule", "anodizing PO schedule", "open outside-processing quantity", "quantity covered by the signed revised promise", "received, canceled, or omitted quantity", "PO line, supplier operation, quantity, and acknowledged date", "anodizer's signed promise", "downstream assembly and cure window", "EA", ("keep_original_promise", "record_signed_revised_promise", "infer_best_case_date"), 1, "anodizer acknowledgment and operation schedule"),
    "Receive accepted plated housings from processing": _s("quantity", "plated housings returned from processing", "supplier shipment quantity", "inspection-accepted quantity with matching outside-processing PO", "rejected, missing, or wrong-lot housings", "PO line, supplier lot, inspection result, and dock count", "supplier replacement date", "receiving and downstream operation window", "EA", ("receive_accepted_quantity", "receive_shipped_quantity", "reject_entire_processed_lot"), 0, "outside-processing receipt and inspection"),
    "Report outside operation completion after receipt": _s("quantity", "outside operation completion", "quantity sent to the supplier operation", "accepted quantity received and available to the order", "rejected, missing, or not-yet-received quantity", "operation completion cannot exceed accepted returned quantity", "supplier recovery for missing units", "next internal operation capacity", "EA", ("complete_accepted_quantity", "complete_sent_quantity", "wait_for_full_return"), 0, "supplier send-receive-yield bridge"),
    "Record yield loss from rejected processed parts": _s("quantity", "outside-processing yield loss", "quantity sent for processing", "accepted processed quantity", "inspection-rejected and missing quantity", "accepted plus rejected plus missing must reconcile to sent quantity", "supplier replacement and credit response", "remaining production requirement", "EA", ("record_verified_yield_loss", "complete_full_sent_quantity", "scrap_unreconciled_difference"), 0, "outside-processing yield reconciliation"),
    "Close an outside-processing PO after final acceptance": _s("quantity", "outside-processing PO closure", "ordered outside-operation quantity", "accepted receipts with fully matched invoice coverage", "rejected, missing, unreceived, or uninvoiced balance", "ordered, sent, accepted, invoiced, and paid quantities must all reconcile", "supplier final statement", "production and accounting close windows", "EA", ("close_fully_reconciled_osp_po", "close_with_open_balance", "leave_settled_po_open"), 0, "outside-processing PO final reconciliation"),
}


VALID_MODES = {"plan", "quantity", "schedule", "financial", "identity", "forecast"}


def validate_decision_specs(titles: set[str]) -> None:
    missing = titles - set(SCENARIO_DECISION_SPECS)
    extra = set(SCENARIO_DECISION_SPECS) - titles
    invalid_modes = {
        title: spec.mode
        for title, spec in SCENARIO_DECISION_SPECS.items()
        if spec.mode not in VALID_MODES
    }
    invalid_options = {
        title: spec.options
        for title, spec in SCENARIO_DECISION_SPECS.items()
        if len(spec.options) != 3 or len(set(spec.options)) != 3
    }
    invalid_recommendations = {
        title: spec.recommended_index
        for title, spec in SCENARIO_DECISION_SPECS.items()
        if spec.recommended_index not in {0, 1, 2}
    }
    if missing or extra or invalid_modes or invalid_options or invalid_recommendations:
        raise ValueError(
            "invalid scenario decision specifications: "
            f"missing={sorted(missing)}, extra={sorted(extra)}, "
            f"modes={invalid_modes}, options={invalid_options}, "
            f"recommendations={invalid_recommendations}"
        )


__all__ = [
    "SCENARIO_DECISION_SPECS",
    "ScenarioDecisionSpec",
    "VALID_MODES",
    "validate_decision_specs",
]
